#!/bin/sh
# although it doesn't seem to be documented,
# current directory appears to be git "main" dir

echo "post-merge hook is executing"

arch="$(uname -m)"
src_make_conf=""
case $arch in
	i686)
	src_make_conf="./conf/intel/portage/make.conf.x86"
	;;
	x86_64)
	src_make_conf="./conf/intel/portage/make.conf.amd64"
	;;
esac

if [ -n "$src_make_conf" ]; then
	echo "post-merge hook: copying make.conf (from $src_make_conf):"
	cp --no-target-directory -v "$src_make_conf" /etc/make.conf
fi

# Copy noarch config files
for conf_file in ./conf/noarch/entropy/packages/* ; do
	dest_path=/etc/entropy/packages/$(basename "${conf_file}")
	echo "Writing ${dest_path}"
	cp --no-target-directory -p -v "${conf_file}" "${dest_path}"
done
