#!/bin/bash

unset PORTAGE
unset PORTAGE_TMPDIR

set -e

if [ "${#}" != "3" ]; then
    echo "Invalid arguments." >&2
    exit 1
fi

CHROOT_PATH="${1}"
ARCH_NAME="${2}"
CHROOT_PREFIX="${3}"

(
    ${CHROOT_PREFIX} chroot "${CHROOT_PATH}" \
	/sabayon/bin/glsa-digest
) | mail -s "[${ARCH_NAME}] GLSA tracker of $(date +%Y-%m-%d)" \
    entropy-team@lists.sabayon.org
